"""Initial schema for backend architecture

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state IN ('active', 'suspended')", name=op.f("ck_user_state")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("access_epoch", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "state IN ('active', 'disabled', 'deleting')", name=op.f("ck_workspace_state")
        ),
        sa.CheckConstraint("access_epoch >= 0", name=op.f("ck_workspace_access_epoch_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace")),
    )
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_auth_session_user_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_session_token_hash")),
    )
    op.create_table(
        "billing_account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("billing_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("state IN ('active', 'blocked')", name=op.f("ck_billing_account_state")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_billing_account_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_account")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_billing_account_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_billing_account_tenant_id")),
    )
    op.create_table(
        "external_identity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_host", sa.Text(), nullable=False),
        sa.Column("external_user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_grant_ref", sa.Text(), nullable=True),
        sa.Column("access_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_external_identity_user_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identity")),
        sa.UniqueConstraint(
            "provider_host",
            "external_user_id",
            name=op.f("uq_external_identity_provider_host_external_user_id"),
        ),
    )
    op.create_table(
        "git_integration",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("provider_host", sa.Text(), nullable=False),
        sa.Column("app_config_key", sa.Text(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("access_epoch", sa.BigInteger(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending', 'active', 'suspended', 'removed')",
            name=op.f("ck_git_integration_state"),
        ),
        sa.CheckConstraint(
            "access_epoch >= 0", name=op.f("ck_git_integration_access_epoch_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_git_integration_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_integration")),
        sa.UniqueConstraint(
            "provider_host",
            "app_config_key",
            "installation_id",
            name=op.f("uq_git_integration_provider_host_app_config_key_installation_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_git_integration_tenant_id_id")),
    )
    op.create_table(
        "membership",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("access_epoch", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer', 'billing_manager')",
            name=op.f("ck_membership_role"),
        ),
        sa.CheckConstraint(
            "state IN ('active', 'suspended', 'revoked')", name=op.f("ck_membership_state")
        ),
        sa.CheckConstraint(
            "access_epoch >= 0", name=op.f("ck_membership_access_epoch_nonnegative")
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_membership_tenant_id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_membership_user_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_membership_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "user_id", name=op.f("uq_membership_tenant_id_user_id")),
    )
    op.create_table(
        "perspective",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint("state IN ('active', 'archived')", name=op.f("ck_perspective_state")),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_perspective_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_perspective")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_perspective_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "key", name=op.f("uq_perspective_tenant_id_key")),
    )
    op.create_table(
        "review_profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_review_profile_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_profile")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_review_profile_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_review_profile_tenant_id_name")),
    )
    op.create_index(
        "uq_review_profile_default",
        "review_profile",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "webhook_inbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_scope", sa.Text(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('received', 'processing', 'applied', 'rejected', 'manual_required')",
            name=op.f("ck_webhook_inbox_state"),
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_webhook_inbox_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_inbox")),
        sa.UniqueConstraint(
            "provider_scope",
            "delivery_id",
            name=op.f("uq_webhook_inbox_provider_scope_delivery_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_webhook_inbox_tenant_id_id")),
    )
    op.create_table(
        "git_connection_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("initiator_id", sa.Uuid(), nullable=False),
        sa.Column("oauth_state_hash", sa.Text(), nullable=False),
        sa.Column("pkce_ref", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending', 'authorized', 'completed', 'rejected')",
            name=op.f("ck_git_connection_session_state"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "initiator_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_git_connection_session_initiator_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_git_connection_session_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_git_connection_session")),
        sa.UniqueConstraint(
            "oauth_state_hash", name=op.f("uq_git_connection_session_oauth_state_hash")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_git_connection_session_tenant_id_id")),
    )
    op.create_table(
        "profile_perspective",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("perspective_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_profile_perspective_position_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "perspective_id"],
            ["perspective.tenant_id", "perspective.id"],
            name="fk_profile_perspective_perspective_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "profile_id"],
            ["review_profile.tenant_id", "review_profile.id"],
            name="fk_profile_perspective_profile_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_profile_perspective_tenant_id"
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "profile_id", "perspective_id", name=op.f("pk_profile_perspective")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "profile_id",
            "position",
            name=op.f("uq_profile_perspective_tenant_id_profile_id_position"),
        ),
    )
    op.create_table(
        "prompt_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("perspective_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_prompt_version_version_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "perspective_id"],
            ["perspective.tenant_id", "perspective.id"],
            name="fk_prompt_version_perspective_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_prompt_version_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_version")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "perspective_id",
            name=op.f("uq_prompt_version_tenant_id_id_perspective_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_prompt_version_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "perspective_id",
            "version",
            name=op.f("uq_prompt_version_tenant_id_perspective_id_version"),
        ),
    )
    op.create_table(
        "repository",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("access_epoch", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "state IN ('active', 'disabled', 'deleting')", name=op.f("ck_repository_state")
        ),
        sa.CheckConstraint(
            "access_epoch >= 0", name=op.f("ck_repository_access_epoch_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "integration_id"],
            ["git_integration.tenant_id", "git_integration.id"],
            name="fk_repository_integration_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_repository_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_repository_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "integration_id",
            "external_id",
            name=op.f("uq_repository_tenant_id_integration_id_external_id"),
        ),
    )
    op.create_table(
        "service_account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("access_epoch", sa.BigInteger(), nullable=False),
        sa.Column("authorized_by_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "state IN ('active', 'disabled')", name=op.f("ck_service_account_state")
        ),
        sa.CheckConstraint(
            "access_epoch >= 0", name=op.f("ck_service_account_access_epoch_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "authorized_by_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_service_account_authorized_by_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_service_account_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_account")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_service_account_tenant_id_id")),
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("billing_account_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_scope", sa.Text(), nullable=False),
        sa.Column("external_subscription_id", sa.Text(), nullable=True),
        sa.Column("renewal_mode", sa.Text(), nullable=False),
        sa.Column("product_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "renewal_mode IN ('automatic', 'manual')", name=op.f("ck_subscription_renewal_mode")
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'active', 'past_due', 'cancelled', 'expired')",
            name=op.f("ck_subscription_state"),
        ),
        sa.CheckConstraint("period_end > period_start", name=op.f("ck_subscription_period")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "billing_account_id"],
            ["billing_account.tenant_id", "billing_account.id"],
            name="fk_subscription_billing_account_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_subscription_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "billing_account_id",
            name=op.f("uq_subscription_tenant_id_id_billing_account_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_subscription_tenant_id_id")),
    )
    op.create_index(
        "uq_subscription_external",
        "subscription",
        ["provider_scope", "external_subscription_id"],
        unique=True,
        postgresql_where=sa.text("external_subscription_id IS NOT NULL"),
    )
    op.create_table(
        "workspace_invitation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_id", sa.Uuid(), nullable=False),
        sa.Column("expected_github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_membership_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending', 'accepted', 'expired', 'revoked')",
            name=op.f("ck_workspace_invitation_state"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "accepted_membership_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_workspace_invitation_accepted_membership_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "invited_by_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_workspace_invitation_invited_by_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_workspace_invitation_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_invitation")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_workspace_invitation_tenant_id_id")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_workspace_invitation_token_hash")),
    )
    op.create_table(
        "merge_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("external_number", sa.BigInteger(), nullable=False),
        sa.Column("revision_descriptor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision_epoch", sa.BigInteger(), nullable=False),
        sa.Column("refresh_requested_seq", sa.BigInteger(), nullable=False),
        sa.Column("refresh_applied_seq", sa.BigInteger(), nullable=False),
        sa.Column("refresh_lease_token", sa.Uuid(), nullable=True),
        sa.Column("refresh_locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "external_number > 0", name=op.f("ck_merge_request_external_number_positive")
        ),
        sa.CheckConstraint(
            "refresh_applied_seq <= refresh_requested_seq",
            name=op.f("ck_merge_request_refresh_sequence"),
        ),
        sa.CheckConstraint(
            "refresh_applied_seq >= 0",
            name=op.f("ck_merge_request_refresh_applied_seq_nonnegative"),
        ),
        sa.CheckConstraint(
            "refresh_requested_seq >= 0",
            name=op.f("ck_merge_request_refresh_requested_seq_nonnegative"),
        ),
        sa.CheckConstraint(
            "revision_epoch >= 0", name=op.f("ck_merge_request_revision_epoch_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "repository_id"],
            ["repository.tenant_id", "repository.id"],
            name="fk_merge_request_repository_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_merge_request_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merge_request")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_merge_request_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "repository_id",
            "external_number",
            name=op.f("uq_merge_request_tenant_id_repository_id_external_number"),
        ),
    )
    op.create_table(
        "purchase",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("billing_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("product_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("accepted_payment_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('awaiting_payment', 'fulfilled', 'cancelled', 'review_required')",
            name=op.f("ck_purchase_state"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_purchase_amount_minor_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "billing_account_id"],
            ["billing_account.tenant_id", "billing_account.id"],
            name="fk_purchase_billing_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "created_by_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_purchase_created_by_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "subscription_id", "billing_account_id"],
            ["subscription.tenant_id", "subscription.id", "subscription.billing_account_id"],
            name="fk_purchase_subscription_id_billing_account_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_purchase_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "billing_account_id",
            name=op.f("uq_purchase_tenant_id_id_billing_account_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchase_tenant_id_id")),
    )
    op.create_index(
        "uq_purchase_renewal",
        "purchase",
        ["tenant_id", "subscription_id", "period_start"],
        unique=True,
        postgresql_where=sa.text("subscription_id IS NOT NULL AND period_start IS NOT NULL"),
    )
    op.create_table(
        "repository_grant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=True),
        sa.Column("service_account_id", sa.Uuid(), nullable=True),
        sa.Column("permission", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "permission IN ('read', 'review', 'manage')",
            name=op.f("ck_repository_grant_permission"),
        ),
        sa.CheckConstraint(
            "state IN ('active', 'revoked')", name=op.f("ck_repository_grant_state")
        ),
        sa.CheckConstraint(
            "(membership_id IS NOT NULL) <> (service_account_id IS NOT NULL)",
            name=op.f("ck_repository_grant_one_actor"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_repository_grant_membership_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "repository_id"],
            ["repository.tenant_id", "repository.id"],
            name="fk_repository_grant_repository_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "service_account_id"],
            ["service_account.tenant_id", "service_account.id"],
            name="fk_repository_grant_service_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_repository_grant_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_grant")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_repository_grant_tenant_id_id")),
    )
    op.create_index(
        "uq_repository_grant_membership_id",
        "repository_grant",
        ["tenant_id", "repository_id", "membership_id"],
        unique=True,
        postgresql_where=sa.text("membership_id IS NOT NULL"),
    )
    op.create_index(
        "uq_repository_grant_service_account_id",
        "repository_grant",
        ["tenant_id", "repository_id", "service_account_id"],
        unique=True,
        postgresql_where=sa.text("service_account_id IS NOT NULL"),
    )
    op.create_table(
        "repository_index",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_oid", sa.Text(), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("graph", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("artifact_hash", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('building', 'ready', 'failed')", name=op.f("ck_repository_index_state")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "repository_id"],
            ["repository.tenant_id", "repository.id"],
            name="fk_repository_index_repository_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_repository_index_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_index")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_repository_index_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "repository_id",
            "commit_oid",
            "config_hash",
            name=op.f("uq_repository_index_tenant_id_repository_id_commit_oid_config_hash"),
        ),
    )
    op.create_table(
        "entitlement",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("billing_account_id", sa.Uuid(), nullable=False),
        sa.Column("source_purchase_id", sa.Uuid(), nullable=False),
        sa.Column("total_units", sa.BigInteger(), nullable=False),
        sa.Column("reserved_units", sa.BigInteger(), nullable=False),
        sa.Column("consumed_units", sa.BigInteger(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('active', 'revoked', 'expired')", name=op.f("ck_entitlement_state")
        ),
        sa.CheckConstraint(
            "consumed_units >= 0", name=op.f("ck_entitlement_consumed_units_nonnegative")
        ),
        sa.CheckConstraint(
            "reserved_units + consumed_units <= total_units", name=op.f("ck_entitlement_capacity")
        ),
        sa.CheckConstraint(
            "reserved_units >= 0", name=op.f("ck_entitlement_reserved_units_nonnegative")
        ),
        sa.CheckConstraint("total_units >= 0", name=op.f("ck_entitlement_total_units_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "billing_account_id"],
            ["billing_account.tenant_id", "billing_account.id"],
            name="fk_entitlement_billing_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_purchase_id", "billing_account_id"],
            ["purchase.tenant_id", "purchase.id", "purchase.billing_account_id"],
            name="fk_entitlement_source_purchase_id_billing_account_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_entitlement_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlement")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "billing_account_id",
            name=op.f("uq_entitlement_tenant_id_id_billing_account_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_entitlement_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "source_purchase_id",
            name=op.f("uq_entitlement_tenant_id_source_purchase_id"),
        ),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_scope", sa.Text(), nullable=False),
        sa.Column("external_payment_id", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("expected_amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('creating', 'pending', 'processing', 'payment_unknown', "
            "'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_payment_state"),
        ),
        sa.CheckConstraint(
            "expected_amount >= 0", name=op.f("ck_payment_expected_amount_nonnegative")
        ),
        sa.CheckConstraint("sequence_no > 0", name=op.f("ck_payment_sequence_no_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "purchase_id"],
            ["purchase.tenant_id", "purchase.id"],
            name="fk_payment_purchase_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_payment_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
        sa.UniqueConstraint(
            "provider_scope",
            "idempotency_key",
            name=op.f("uq_payment_provider_scope_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "tenant_id", "id", "purchase_id", name=op.f("uq_payment_tenant_id_id_purchase_id")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payment_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "purchase_id",
            "sequence_no",
            name=op.f("uq_payment_tenant_id_purchase_id_sequence_no"),
        ),
    )
    op.create_index("ix_payment_available", "payment", ["state", "available_at"], unique=False)
    op.create_index(
        "ix_payment_lease",
        "payment",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("locked_until IS NOT NULL"),
    )
    op.create_index(
        "uq_payment_external",
        "payment",
        ["provider_scope", "external_payment_id"],
        unique=True,
        postgresql_where=sa.text("external_payment_id IS NOT NULL"),
    )
    op.create_index(
        "uq_payment_open_purchase",
        "payment",
        ["tenant_id", "purchase_id"],
        unique=True,
        postgresql_where=sa.text(
            "state IN ('creating', 'pending', 'processing', 'payment_unknown')"
        ),
    )
    op.create_table(
        "review_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("merge_request_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=True),
        sa.Column("actor_service_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reserved_tokens", sa.BigInteger(), nullable=False),
        sa.Column("accounted_tokens", sa.BigInteger(), nullable=False),
        sa.Column("track_latest", sa.Boolean(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('accepted', 'running', 'succeeded', 'partial', 'failed', "
            "'cancelled', 'expired')",
            name=op.f("ck_review_request_state"),
        ),
        sa.CheckConstraint(
            "(actor_membership_id IS NOT NULL) <> (actor_service_id IS NOT NULL)",
            name=op.f("ck_review_request_one_actor"),
        ),
        sa.CheckConstraint(
            "accounted_tokens >= 0", name=op.f("ck_review_request_accounted_tokens_nonnegative")
        ),
        sa.CheckConstraint(
            "reserved_tokens >= 0", name=op.f("ck_review_request_reserved_tokens_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_membership_id"],
            ["membership.tenant_id", "membership.id"],
            name="fk_review_request_actor_membership_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_service_id"],
            ["service_account.tenant_id", "service_account.id"],
            name="fk_review_request_actor_service_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "merge_request_id"],
            ["merge_request.tenant_id", "merge_request.id"],
            name="fk_review_request_merge_request_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_review_request_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_request")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "merge_request_id",
            name=op.f("uq_review_request_tenant_id_id_merge_request_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_review_request_tenant_id_id")),
    )
    op.create_index(
        "uq_review_request_actor_membership_id",
        "review_request",
        ["tenant_id", "actor_membership_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("actor_membership_id IS NOT NULL"),
    )
    op.create_index(
        "uq_review_request_actor_service_id",
        "review_request",
        ["tenant_id", "actor_service_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("actor_service_id IS NOT NULL"),
    )
    op.create_table(
        "review_job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("merge_request_id", sa.Uuid(), nullable=False),
        sa.Column("index_id", sa.Uuid(), nullable=True),
        sa.Column("revision_fingerprint", sa.Text(), nullable=False),
        sa.Column("revision_epoch", sa.BigInteger(), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("phase", sa.Text(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'partial', 'failed', "
            "'cancelled', 'superseded', 'expired')",
            name=op.f("ck_review_job_state"),
        ),
        sa.CheckConstraint(
            "revision_epoch >= 0", name=op.f("ck_review_job_revision_epoch_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "index_id"],
            ["repository_index.tenant_id", "repository_index.id"],
            name="fk_review_job_index_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "request_id", "merge_request_id"],
            ["review_request.tenant_id", "review_request.id", "review_request.merge_request_id"],
            name="fk_review_job_request_id_merge_request_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_review_job_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_job")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_review_job_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "request_id",
            "revision_epoch",
            "revision_fingerprint",
            "config_hash",
            name=op.f(
                "uq_review_job_tenant_id_request_id_revision_epoch_revision_fingerprint_config_hash"
            ),
        ),
    )
    op.create_index(
        "uq_review_job_active_request",
        "review_job",
        ["request_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    op.create_table(
        "usage_reservation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("entitlement_id", sa.Uuid(), nullable=False),
        sa.Column("units", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(state = 'reserved' AND settled_at IS NULL) OR (state IN ('consumed', "
            "'released') AND settled_at IS NOT NULL)",
            name=op.f("ck_usage_reservation_settlement"),
        ),
        sa.CheckConstraint(
            "state IN ('reserved', 'consumed', 'released')", name=op.f("ck_usage_reservation_state")
        ),
        sa.CheckConstraint("units > 0", name=op.f("ck_usage_reservation_units_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "entitlement_id"],
            ["entitlement.tenant_id", "entitlement.id"],
            name="fk_usage_reservation_entitlement_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "request_id"],
            ["review_request.tenant_id", "review_request.id"],
            name="fk_usage_reservation_request_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_usage_reservation_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_reservation")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "entitlement_id",
            name=op.f("uq_usage_reservation_tenant_id_id_entitlement_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_usage_reservation_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "request_id", name=op.f("uq_usage_reservation_tenant_id_request_id")
        ),
    )
    op.create_table(
        "billing_entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("billing_account_id", sa.Uuid(), nullable=False),
        sa.Column("entitlement_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("business_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('grant', 'reserve', 'consume', 'release', 'adjustment')",
            name=op.f("ck_billing_entry_kind"),
        ),
        sa.CheckConstraint(
            "kind NOT IN ('reserve', 'consume', 'release') OR reservation_id IS NOT NULL",
            name=op.f("ck_billing_entry_reservation_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "billing_account_id"],
            ["billing_account.tenant_id", "billing_account.id"],
            name="fk_billing_entry_billing_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "entitlement_id", "billing_account_id"],
            ["entitlement.tenant_id", "entitlement.id", "entitlement.billing_account_id"],
            name="fk_billing_entry_entitlement_id_billing_account_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reservation_id", "entitlement_id"],
            [
                "usage_reservation.tenant_id",
                "usage_reservation.id",
                "usage_reservation.entitlement_id",
            ],
            name="fk_billing_entry_reservation_id_entitlement_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_billing_entry_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_entry")),
        sa.UniqueConstraint(
            "tenant_id",
            "billing_account_id",
            "business_key",
            name=op.f("uq_billing_entry_tenant_id_billing_account_id_business_key"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_billing_entry_tenant_id_id")),
    )
    op.create_index(
        "uq_billing_entry_settlement",
        "billing_entry",
        ["tenant_id", "reservation_id"],
        unique=True,
        postgresql_where=sa.text("kind IN ('consume', 'release')"),
    )
    op.create_table(
        "perspective_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("perspective_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'not_applicable', "
            "'insufficient_context', 'failed', 'cancelled')",
            name=op.f("ck_perspective_run_state"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["review_job.tenant_id", "review_job.id"],
            name="fk_perspective_run_job_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "perspective_id"],
            ["perspective.tenant_id", "perspective.id"],
            name="fk_perspective_run_perspective_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "prompt_version_id", "perspective_id"],
            ["prompt_version.tenant_id", "prompt_version.id", "prompt_version.perspective_id"],
            name="fk_perspective_run_prompt_version_id_perspective_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_perspective_run_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_perspective_run")),
        sa.UniqueConstraint(
            "tenant_id", "id", "job_id", name=op.f("uq_perspective_run_tenant_id_id_job_id")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_perspective_run_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "job_id",
            "perspective_id",
            name=op.f("uq_perspective_run_tenant_id_job_id_perspective_id"),
        ),
    )
    op.create_table(
        "work_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=True),
        sa.Column("merge_request_id", sa.Uuid(), nullable=True),
        sa.Column("review_request_id", sa.Uuid(), nullable=True),
        sa.Column("review_job_id", sa.Uuid(), nullable=True),
        sa.Column("business_key", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'index_repository' AND repository_id IS NOT NULL AND "
            "merge_request_id IS NULL AND review_request_id IS NULL AND review_job_id IS "
            "NULL) OR (kind = 'sync_revision' AND repository_id IS NULL AND "
            "merge_request_id IS NOT NULL AND review_request_id IS NULL AND "
            "review_job_id IS NULL) OR (kind = 'resolve_review' AND repository_id IS "
            "NULL AND merge_request_id IS NULL AND review_request_id IS NOT NULL AND "
            "review_job_id IS NULL) OR (kind = 'run_review' AND repository_id IS NULL "
            "AND merge_request_id IS NULL AND review_request_id IS NULL AND "
            "review_job_id IS NOT NULL)",
            name=op.f("ck_work_item_kind_target"),
        ),
        sa.CheckConstraint(
            "kind IN ('index_repository', 'resolve_review', 'run_review', 'sync_revision')",
            name=op.f("ck_work_item_kind"),
        ),
        sa.CheckConstraint(
            "state <> 'running' OR (lease_token IS NOT NULL AND locked_until IS NOT NULL)",
            name=op.f("ck_work_item_running_lease"),
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'retry_wait', 'waiting_external', "
            "'succeeded', 'cancelled', 'failed')",
            name=op.f("ck_work_item_state"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_work_item_attempt_count_nonnegative")
        ),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_work_item_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "merge_request_id"],
            ["merge_request.tenant_id", "merge_request.id"],
            name="fk_work_item_merge_request_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "repository_id"],
            ["repository.tenant_id", "repository.id"],
            name="fk_work_item_repository_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "review_job_id"],
            ["review_job.tenant_id", "review_job.id"],
            name="fk_work_item_review_job_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "review_request_id"],
            ["review_request.tenant_id", "review_request.id"],
            name="fk_work_item_review_request_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_work_item_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_item")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_work_item_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "kind",
            "business_key",
            name=op.f("uq_work_item_tenant_id_kind_business_key"),
        ),
    )
    op.create_index("ix_work_item_available", "work_item", ["state", "available_at"], unique=False)
    op.create_index(
        "ix_work_item_lease",
        "work_item",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("locked_until IS NOT NULL"),
    )
    op.create_table(
        "model_call",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("perspective_run_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("call_key", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("accepted_attempt_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'job_synthesis' AND perspective_run_id IS NULL) OR (kind IN "
            "('chunk', 'perspective_synthesis') AND perspective_run_id IS NOT NULL)",
            name=op.f("ck_model_call_perspective_kind"),
        ),
        sa.CheckConstraint(
            "kind IN ('chunk', 'perspective_synthesis', 'job_synthesis')",
            name=op.f("ck_model_call_kind"),
        ),
        sa.CheckConstraint(
            "state IN ('planned', 'ready', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_model_call_state"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["review_job.tenant_id", "review_job.id"],
            name="fk_model_call_job_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "perspective_run_id", "job_id"],
            ["perspective_run.tenant_id", "perspective_run.id", "perspective_run.job_id"],
            name="fk_model_call_perspective_run_id_job_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_model_call_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_call")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "accepted_attempt_id",
            name=op.f("uq_model_call_tenant_id_id_accepted_attempt_id"),
        ),
        sa.UniqueConstraint(
            "tenant_id", "id", "job_id", name=op.f("uq_model_call_tenant_id_id_job_id")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_model_call_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "job_id", "call_key", name=op.f("uq_model_call_tenant_id_job_id_call_key")
        ),
    )
    op.create_table(
        "context_payload",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("model_call_id", sa.Uuid(), nullable=False),
        sa.Column("request_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("token_count", sa.BigInteger(), nullable=False),
        sa.Column("output_reserve", sa.BigInteger(), nullable=False),
        sa.Column("counter_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "output_reserve >= 0", name=op.f("ck_context_payload_output_reserve_nonnegative")
        ),
        sa.CheckConstraint(
            "token_count >= 0", name=op.f("ck_context_payload_token_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "model_call_id"],
            ["model_call.tenant_id", "model_call.id"],
            name="fk_context_payload_model_call_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_context_payload_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_payload")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_context_payload_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "model_call_id", name=op.f("uq_context_payload_tenant_id_model_call_id")
        ),
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("model_call_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("duplicate_of_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "duplicate_of_id IS NULL OR duplicate_of_id <> id",
            name=op.f("ck_finding_not_self_duplicate"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id", "duplicate_of_id"],
            ["finding.tenant_id", "finding.job_id", "finding.id"],
            name="fk_finding_job_id_duplicate_of_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["review_job.tenant_id", "review_job.id"],
            name="fk_finding_job_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "model_call_id", "attempt_id"],
            ["model_call.tenant_id", "model_call.id", "model_call.accepted_attempt_id"],
            name="fk_finding_model_call_id_attempt_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "model_call_id", "job_id"],
            ["model_call.tenant_id", "model_call.id", "model_call.job_id"],
            name="fk_finding_model_call_id_job_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_finding_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_finding_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "job_id", "id", name=op.f("uq_finding_tenant_id_job_id_id")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "model_call_id",
            "fingerprint",
            name=op.f("uq_finding_tenant_id_model_call_id_fingerprint"),
        ),
    )
    op.create_table(
        "inference_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("model_call_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("owner_token", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("reserved_tokens", sa.BigInteger(), nullable=False),
        sa.Column("actual_tokens", sa.BigInteger(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "state IN ('prepared', 'sending', 'received', 'accepted', 'failed', "
            "'outcome_unknown', 'rejected')",
            name=op.f("ck_inference_attempt_state"),
        ),
        sa.CheckConstraint(
            "actual_tokens >= 0", name=op.f("ck_inference_attempt_actual_tokens_nonnegative")
        ),
        sa.CheckConstraint("attempt_no > 0", name=op.f("ck_inference_attempt_attempt_no_positive")),
        sa.CheckConstraint(
            "reserved_tokens >= 0", name=op.f("ck_inference_attempt_reserved_tokens_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "model_call_id"],
            ["model_call.tenant_id", "model_call.id"],
            name="fk_inference_attempt_model_call_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "work_item_id"],
            ["work_item.tenant_id", "work_item.id"],
            name="fk_inference_attempt_work_item_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["workspace.id"], name="fk_inference_attempt_tenant_id"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inference_attempt")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "model_call_id",
            name=op.f("uq_inference_attempt_tenant_id_id_model_call_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_inference_attempt_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "model_call_id",
            "attempt_no",
            name=op.f("uq_inference_attempt_tenant_id_model_call_id_attempt_no"),
        ),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.Column("publication_key", sa.Text(), nullable=False),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("provider_comment_id", sa.Text(), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('pending', 'publishing', 'published', 'retry_wait', "
            "'delivery_unknown', 'failed', 'skipped')",
            name=op.f("ck_comment_state"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id", "finding_id"],
            ["finding.tenant_id", "finding.job_id", "finding.id"],
            name="fk_comment_job_id_finding_id",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "job_id"],
            ["review_job.tenant_id", "review_job.id"],
            name="fk_comment_job_id",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["workspace.id"], name="fk_comment_tenant_id"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_comment_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "job_id",
            "publication_key",
            name=op.f("uq_comment_tenant_id_job_id_publication_key"),
        ),
    )
    op.create_index("ix_comment_available", "comment", ["state", "available_at"], unique=False)
    op.create_index(
        "ix_comment_lease",
        "comment",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("locked_until IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # Cyclic references must be added after both endpoints exist.
    op.create_foreign_key(
        "fk_purchase_accepted_payment_id_id",
        "purchase",
        "payment",
        ["tenant_id", "accepted_payment_id", "id"],
        ["tenant_id", "id", "purchase_id"],
    )
    op.create_foreign_key(
        "fk_model_call_accepted_attempt_id_id",
        "model_call",
        "inference_attempt",
        ["tenant_id", "accepted_attempt_id", "id"],
        ["tenant_id", "id", "model_call_id"],
    )


def downgrade() -> None:
    op.drop_constraint("fk_model_call_accepted_attempt_id_id", "model_call", type_="foreignkey")
    op.drop_constraint("fk_purchase_accepted_payment_id_id", "purchase", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_comment_lease",
        table_name="comment",
        postgresql_where=sa.text("locked_until IS NOT NULL"),
    )
    op.drop_index("ix_comment_available", table_name="comment")
    op.drop_table("comment")
    op.drop_table("inference_attempt")
    op.drop_table("finding")
    op.drop_table("context_payload")
    op.drop_table("model_call")
    op.drop_index(
        "ix_work_item_lease",
        table_name="work_item",
        postgresql_where=sa.text("locked_until IS NOT NULL"),
    )
    op.drop_index("ix_work_item_available", table_name="work_item")
    op.drop_table("work_item")
    op.drop_table("perspective_run")
    op.drop_index(
        "uq_billing_entry_settlement",
        table_name="billing_entry",
        postgresql_where=sa.text("kind IN ('consume', 'release')"),
    )
    op.drop_table("billing_entry")
    op.drop_table("usage_reservation")
    op.drop_index(
        "uq_review_job_active_request",
        table_name="review_job",
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    op.drop_table("review_job")
    op.drop_index(
        "uq_review_request_actor_service_id",
        table_name="review_request",
        postgresql_where=sa.text("actor_service_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_review_request_actor_membership_id",
        table_name="review_request",
        postgresql_where=sa.text("actor_membership_id IS NOT NULL"),
    )
    op.drop_table("review_request")
    op.drop_index(
        "uq_payment_open_purchase",
        table_name="payment",
        postgresql_where=sa.text(
            "state IN ('creating', 'pending', 'processing', 'payment_unknown')"
        ),
    )
    op.drop_index(
        "uq_payment_external",
        table_name="payment",
        postgresql_where=sa.text("external_payment_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_payment_lease",
        table_name="payment",
        postgresql_where=sa.text("locked_until IS NOT NULL"),
    )
    op.drop_index("ix_payment_available", table_name="payment")
    op.drop_table("payment")
    op.drop_table("entitlement")
    op.drop_table("repository_index")
    op.drop_index(
        "uq_repository_grant_service_account_id",
        table_name="repository_grant",
        postgresql_where=sa.text("service_account_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_repository_grant_membership_id",
        table_name="repository_grant",
        postgresql_where=sa.text("membership_id IS NOT NULL"),
    )
    op.drop_table("repository_grant")
    op.drop_index(
        "uq_purchase_renewal",
        table_name="purchase",
        postgresql_where=sa.text("subscription_id IS NOT NULL AND period_start IS NOT NULL"),
    )
    op.drop_table("purchase")
    op.drop_table("merge_request")
    op.drop_table("workspace_invitation")
    op.drop_index(
        "uq_subscription_external",
        table_name="subscription",
        postgresql_where=sa.text("external_subscription_id IS NOT NULL"),
    )
    op.drop_table("subscription")
    op.drop_table("service_account")
    op.drop_table("repository")
    op.drop_table("prompt_version")
    op.drop_table("profile_perspective")
    op.drop_table("git_connection_session")
    op.drop_table("webhook_inbox")
    op.drop_index(
        "uq_review_profile_default",
        table_name="review_profile",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("review_profile")
    op.drop_table("perspective")
    op.drop_table("membership")
    op.drop_table("git_integration")
    op.drop_table("external_identity")
    op.drop_table("billing_account")
    op.drop_table("auth_session")
    op.drop_table("workspace")
    op.drop_table("user")
    # ### end Alembic commands ###
