"""Export reproducible physical ER diagrams from SQLAlchemy metadata."""

from pathlib import Path

from sqlalchemy.dialects import postgresql

from code_review.adapters.outbound.postgres import models  # noqa: F401
from code_review.adapters.outbound.postgres.base import Base

ROOT = Path(__file__).resolve().parents[1]
GROUPS = {
    "identity": [
        "user",
        "external_identity",
        "auth_session",
        "workspace",
        "membership",
        "workspace_invitation",
        "service_account",
    ],
    "github": [
        "git_integration",
        "git_connection_session",
        "repository",
        "repository_grant",
        "merge_request",
        "repository_index",
    ],
    "review": [
        "review_profile",
        "perspective",
        "profile_perspective",
        "prompt_version",
        "review_request",
        "review_job",
        "perspective_run",
    ],
    "execution": [
        "model_call",
        "context_payload",
        "inference_attempt",
        "finding",
        "comment",
        "work_item",
        "webhook_inbox",
    ],
    "billing": [
        "billing_account",
        "subscription",
        "purchase",
        "payment",
        "entitlement",
        "usage_reservation",
        "billing_entry",
    ],
}


def diagram(names):
    lines = ["erDiagram"]
    for name in names:
        table = Base.metadata.tables[name]
        lines.append(f"    {name} {{")
        for col in table.columns:
            typename = str(col.type.compile(dialect=postgresql.dialect())).lower()
            typename = typename.replace("timestamp with time zone", "timestamptz")
            keys = [
                label
                for condition, label in [(col.primary_key, "PK"), (bool(col.foreign_keys), "FK")]
                if condition
            ]
            suffix = " " + ",".join(keys) if keys else ""
            nullable = "NULL" if col.nullable else "NOT NULL"
            lines.append(f'        {typename} {col.name}{suffix} "{nullable}"')
        lines.append("    }")
    for name in names:
        table = Base.metadata.tables[name]
        for fk in sorted(table.foreign_key_constraints, key=lambda item: item.name):
            # Optionality is determined by the non-tenant components of a composite FK.
            optional = any(col.nullable for col in fk.columns)
            parent = "o|" if optional else "||"
            label = ",".join(col.name for col in fk.columns)
            lines.append(f'    {fk.referred_table.name} {parent}--o{{ {name} : "{label}"')
    return "\n".join(lines) + "\n"


def artifacts():
    result = {"physical.mmd": diagram(sorted(Base.metadata.tables))}
    for group, names in GROUPS.items():
        source = diagram(names)
        result[f"{group}.mmd"] = source
        result[f"{group}.md"] = (
            f"# Physical schema: {group}\n\n"
            "Generated by `uv run python scripts/export_erd.py`.\n"
            "External parent tables are shown as references.\n\n"
            f"```mermaid\n{source}```\n"
        )
    return result


if __name__ == "__main__":
    folder = ROOT / "docs/erd"
    folder.mkdir(parents=True, exist_ok=True)
    for filename, content in artifacts().items():
        (folder / filename).write_text(content)
